import { useState } from 'react';
import type { MouseEvent } from 'react';
import { Button, Card, DatePicker, Descriptions, Divider, Drawer, Dropdown, Empty, Form, Input, Menu, Modal, Select, Switch, Table, Tag, Message } from '../components/ui';
import { IconCopy, IconDelete, IconMore, IconPlus } from '@arco-design/web-react/icon';
import { RichTextEditor } from '../components/RichTextEditor';
import { PdfDocumentIcon } from '../components/PdfDocumentIcon';
import { KNOWLEDGE_DOCUMENT_MAX_SIZE, KnowledgeFileModal } from './ModulePages';
import { updateFlow, updateGuards, useAppStore } from '../store';
import { now } from '../mockData';
import type { Agent, EnvironmentVariable, Flow, Guard, KnowledgeDocument, Session } from '../types';

const makeId = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
const formatDate = (value: string) => value.replace('T', ' ').slice(0, 16);
const detailSkillDescriptions: Record<string, string> = {
  'skill-order': '查询订单状态、物流进度和预计送达时间，支持按订单号返回配送状态，并补充异常物流节点、退款进度和客户追问所需的处理建议。',
  'skill-ticket': '为客户创建售后工单并返回工单编号，支持记录问题和处理结果，同时补充问题分类、优先级、跟进节点和处理时限。',
  'skill-customer': '根据客户标识查询会员等级和服务记录，辅助判断客户服务权益，并结合历史咨询、订单状态和服务规则给出匹配结果。',
};

export function FlowSectionV2({ agent }: { agent: Agent }) {
  const { dispatch } = useAppStore();
  const toast = Message;
  const [selectedId, setSelectedId] = useState(agent.draft.flows[0]?.id);
  const [query, setQuery] = useState('');
  const selected = agent.draft.flows.find((flow) => flow.id === selectedId);
  const saveFlow = (patch: Partial<Flow>) => { if (!selected) return; dispatch({ type: 'agent.config', id: agent.id, config: updateFlow(agent.draft, { ...selected, ...patch, updatedAt: now() }) }); };
  const create = () => { const flow: Flow = { id: makeId('flow'), name: '未命名流程', trigger: '', content: '', contentHtml: '<p></p>', updatedAt: now() }; dispatch({ type: 'agent.config', id: agent.id, config: { ...agent.draft, flows: [...agent.draft.flows, flow] } }); setSelectedId(flow.id); };
  const copy = (flow: Flow) => { const copyFlow = { ...flow, id: makeId('flow'), name: `${flow.name} 副本`, updatedAt: now() }; dispatch({ type: 'agent.config', id: agent.id, config: { ...agent.draft, flows: [...agent.draft.flows, copyFlow] } }); setSelectedId(copyFlow.id); toast.success('流程已复制'); };
  const remove = (flow: Flow) => { const flows = agent.draft.flows.filter((item) => item.id !== flow.id); dispatch({ type: 'agent.config', id: agent.id, config: { ...agent.draft, flows } }); setSelectedId(flows[0]?.id); toast.success('流程已删除'); };
  const visibleFlows = agent.draft.flows.filter((flow) => flow.name.toLowerCase().includes(query.toLowerCase()));
  return <div className="detail-split-page flow-page"><aside className="detail-resource-list"><div className="detail-list-head"><h2>流程</h2><Button type="text" shape="circle" icon={<IconPlus />} aria-label="新增流程" onClick={create} /></div><div className="flow-list-module"><Input.Search value={query} onChange={setQuery} placeholder="搜索流程" allowClear /><div className="detail-list-items">{visibleFlows.map((flow) => <div className={`detail-list-item ${flow.id === selectedId ? 'active' : ''}`} key={flow.id} onClick={() => setSelectedId(flow.id)}><span className="detail-list-dot" /><span>{flow.name}</span><Dropdown droplist={<Menu><Menu.Item key="copy" onClick={(event: MouseEvent) => { event.stopPropagation(); copy(flow); }}><IconCopy /> 复制</Menu.Item><Menu.Item key="delete" className="danger-menu-item" onClick={(event: MouseEvent) => { event.stopPropagation(); remove(flow); }}><IconDelete /> 删除</Menu.Item></Menu>} trigger="click"><Button type="text" className="table-more-button" icon={<IconMore />} aria-label={`${flow.name} 更多操作`} onClick={(event: MouseEvent) => event.stopPropagation()} /></Dropdown></div>)}</div>{!visibleFlows.length && <Empty description={agent.draft.flows.length ? '未找到流程' : '暂无流程'}><Button type="primary" onClick={create}>新增流程</Button></Empty>}</div></aside><section className="detail-resource-editor flow-config-editor">{selected ? <Form layout="vertical"><Form.Item label="流程名称"><Input value={selected.name} maxLength={50} onChange={(value: string) => saveFlow({ name: value })} /></Form.Item><Divider /><Form.Item label="触发条件"><Input.TextArea value={selected.trigger} maxLength={500} showCount onChange={(value: string) => saveFlow({ trigger: value })} /></Form.Item><Divider /><Form.Item label="内容"><RichTextEditor value={selected.contentHtml || selected.content} onChange={(contentHtml, content) => saveFlow({ contentHtml, content })} /></Form.Item></Form> : <Empty description="选择一个流程开始配置" />}</section></div>;
}

export function SkillSectionV2({ agent }: { agent: Agent }) {
  const { state, dispatch } = useAppStore();
  const toast = Message;
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState('');
  const [pageQuery, setPageQuery] = useState('');
  const attached = state.skills.filter((skill) => agent.draft.skillIds.includes(skill.id));
  const visibleAttached = attached.filter((skill) => `${skill.name}${skill.description}`.toLowerCase().includes(pageQuery.toLowerCase()));
  const available = state.skills.filter((skill) => skill.enabled && !agent.draft.skillIds.includes(skill.id) && `${skill.name}${skill.description}`.toLowerCase().includes(query.toLowerCase()));
  const addSkill = (skillId: string) => { dispatch({ type: 'agent.config', id: agent.id, config: { ...agent.draft, skillIds: [...agent.draft.skillIds, skillId] } }); setOpen(false); setQuery(''); toast.success('技能已添加'); };
  const detach = (skillId: string) => { dispatch({ type: 'agent.config', id: agent.id, config: { ...agent.draft, skillIds: agent.draft.skillIds.filter((id) => id !== skillId) } }); toast.success('技能已分离'); };
  return <div className="detail-resource-page"><div className="detail-toolbar"><h1 className="resource-page-title">技能</h1><Button type="primary" icon={<IconPlus />} onClick={() => setOpen(true)}>绑定技能</Button></div><Input.Search className="resource-page-search" value={pageQuery} onChange={setPageQuery} placeholder="搜索技能" allowClear />{visibleAttached.length ? <div className="resource-grid skill-resource-grid">{visibleAttached.map((skill) => <Card key={skill.id} className="resource-card skill-card"><div className="skill-card-head"><div className="module-name-cell"><span className="skill-avatar">{skill.name.slice(0, 1).toUpperCase()}</span><div><strong>{skill.name}</strong></div></div></div><p className="agent-description skill-description">{detailSkillDescriptions[skill.id] || skill.description}</p><div className="skill-card-footer"><Dropdown droplist={<Menu><Menu.Item key="detach" className="danger-menu-item" onClick={() => Modal.confirm({ title: '分离智能体？', content: '分离后，该智能体将不再使用此技能。', onOk: () => detach(skill.id) })}>分离智能体</Menu.Item></Menu>} trigger="click"><Button type="text" className="skill-more-button" icon={<IconMore />} aria-label={`${skill.name} 更多操作`} /></Dropdown></div></Card>)}</div> : <Empty description={attached.length ? '未找到技能' : '当前智能体尚未添加技能'} /> }<Modal open={open} title="添加技能" onCancel={() => { setOpen(false); setQuery(''); }} footer={null} className="resource-picker-modal"><Input.Search value={query} onChange={setQuery} placeholder="搜索技能" allowClear /><div className="resource-picker-list">{available.map((skill) => <button type="button" className="skill-picker-item" key={skill.id} onClick={() => addSkill(skill.id)}><span className="skill-avatar">{skill.name.slice(0, 1)}</span><span><strong>{skill.name}</strong><small>{skill.description}</small></span></button>)}</div>{!available.length && <Empty description="暂无可添加技能" />}</Modal></div>;
}

export function KnowledgeSectionV2({ agent }: { agent: Agent }) {
  const { state, dispatch } = useAppStore();
  const toast = Message;
  const [open, setOpen] = useState(false);
  const [fileOpen, setFileOpen] = useState(false);
  const [removing, setRemoving] = useState<KnowledgeDocument>();
  const [query, setQuery] = useState('');
  const [pageQuery, setPageQuery] = useState('');
  const attached = state.documents.filter((doc) => doc.type === 'PDF' && agent.draft.knowledgeIds.includes(doc.id));
  const visibleAttached = attached.filter((doc) => doc.name.toLowerCase().includes(pageQuery.toLowerCase()));
  const available = state.documents.filter((doc) => doc.type === 'PDF' && doc.status === 'success' && !agent.draft.knowledgeIds.includes(doc.id) && doc.name.toLowerCase().includes(query.toLowerCase()));
  const addDocument = (documentId: string) => { dispatch({ type: 'agent.config', id: agent.id, config: { ...agent.draft, knowledgeIds: [...agent.draft.knowledgeIds, documentId] } }); setOpen(false); setQuery(''); toast.success('文档已绑定'); };
  const detach = (documentId: string) => { dispatch({ type: 'agent.config', id: agent.id, config: { ...agent.draft, knowledgeIds: agent.draft.knowledgeIds.filter((id) => id !== documentId) } }); toast.success('文档已移除'); };
  const addFiles = (files: File[]) => {
    let accepted = 0;
    for (const file of files) {
      if (file.name.split('.').pop()?.toUpperCase() !== 'PDF') { toast.error(`${file.name} 仅支持 PDF 文档`); continue; }
      if (file.size > KNOWLEDGE_DOCUMENT_MAX_SIZE) { toast.error(`${file.name} 超过 50 MB 限制`); continue; }
      const createdAt = now();
      const document: KnowledgeDocument = { id: makeId('doc'), type: 'PDF', name: file.name, source: file.name, size: file.size, creator: '当前用户', status: 'adding', content: '正在上传文档……', createdAt, updatedAt: createdAt };
      dispatch({ type: 'document.add', document });
      accepted += 1;
      window.setTimeout(() => dispatch({ type: 'document.update', id: document.id, patch: { content: '正在切片处理……' } }), 450);
      window.setTimeout(() => dispatch({ type: 'document.update', id: document.id, patch: { content: '正在进行数据处理……' } }), 900);
      window.setTimeout(() => dispatch({ type: 'document.update', id: document.id, patch: { status: 'success', content: `文档「${file.name}」处理成功。` } }), 1400);
    }
    if (accepted) toast.success('文档已加入处理队列');
  };
  return <div className="detail-resource-page"><div className="detail-toolbar"><h1 className="resource-page-title">知识库</h1><Button type="primary" icon={<IconPlus />} onClick={() => setOpen(true)}>绑定文档</Button></div><Input.Search className="resource-page-search" value={pageQuery} onChange={setPageQuery} placeholder="搜索文档" allowClear /><Table rowKey="id" dataSource={visibleAttached} pagination={false} noDataElement={<Empty description={attached.length ? '未找到文档' : '当前 AI客服尚未绑定文档'} />} columns={[{ title: '名称', dataIndex: 'name', render: (value: string) => <div className="module-name-cell"><PdfDocumentIcon /><strong>{value}</strong></div> }, { title: '创建者', dataIndex: 'creator' }, { title: '创建时间', dataIndex: 'createdAt', render: (_: unknown, document: KnowledgeDocument) => formatDate(document.createdAt || document.updatedAt) }, { title: '操作', width: 56, render: (_: unknown, document: KnowledgeDocument) => <Button type="text" danger className="document-remove-button" icon={<IconDelete />} aria-label={`移除文档：${document.name}`} onClick={() => setRemoving(document)} /> }]} /><Modal open={open} title="绑定文档" onCancel={() => { setOpen(false); setQuery(''); }} footer={null} className="resource-picker-modal"><div className="document-picker-toolbar"><Input.Search value={query} onChange={setQuery} placeholder="搜索文档" allowClear /><Button className="document-picker-add" onClick={() => setFileOpen(true)}>添加文档</Button></div><div className="resource-picker-list">{available.map((document) => <button type="button" className="knowledge-picker-item" key={document.id} onClick={() => addDocument(document.id)}><PdfDocumentIcon /><strong>{document.name}</strong></button>)}</div>{!available.length && <Empty description="暂无可绑定文档" />}</Modal><Modal open={Boolean(removing)} title="移除文档？" onCancel={() => setRemoving(undefined)} onOk={() => { if (removing) detach(removing.id); setRemoving(undefined); }} okText="移除">移除后，该 AI客服将不再使用此文档。</Modal><KnowledgeFileModal open={fileOpen} onClose={() => setFileOpen(false)} onAdd={addFiles} /></div>;
}

export function GuardsSectionV2({ agent }: { agent: Agent }) {
  const { dispatch } = useAppStore(); const toast = Message; const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Guard>(); const [action, setAction] = useState<Guard['action']>('fixed'); const [form] = Form.useForm();
  const save = async () => { const values = await form.validateFields(); const item: Guard = { id: editing?.id || makeId('guard'), name: values.name, prompt: values.prompt, action: values.action, fixedReply: values.action === 'fixed' ? values.fixedReply || '' : '', enabled: values.enabled ?? true, updatedAt: now() }; const guards = editing ? agent.draft.guards.map((guard) => guard.id === editing.id ? item : guard) : [...agent.draft.guards, item]; dispatch({ type: 'agent.config', id: agent.id, config: updateGuards(agent.draft, guards) }); setOpen(false); toast.success(editing ? '防护措施已更新' : '防护措施已创建'); };
  const openEdit = (guard?: Guard) => { const nextAction = guard?.action || 'fixed'; setEditing(guard); setAction(nextAction); form.resetFields(); if (guard) form.setFieldsValue(guard); else form.setFieldsValue({ action: 'fixed', enabled: true }); setOpen(true); };
  const toggleEnabled = (item: Guard, enabled: boolean) => { const guards = agent.draft.guards.map((guard) => guard.id === item.id ? { ...guard, enabled, updatedAt: now() } : guard); dispatch({ type: 'agent.config', id: agent.id, config: updateGuards(agent.draft, guards) }); };
  const more = (item: Guard) => <Menu><Menu.Item key="edit" onClick={() => openEdit(item)}>编辑</Menu.Item><Menu.Item key="copy" onClick={() => { const copy = { ...item, id: makeId('guard'), name: `${item.name} 副本`, updatedAt: now() }; dispatch({ type: 'agent.config', id: agent.id, config: updateGuards(agent.draft, [...agent.draft.guards, copy]) }); toast.success('防护措施已复制'); }}>复制</Menu.Item><Menu.Item key="delete" className="danger-menu-item" onClick={() => Modal.confirm({ title: '删除防护措施？', content: '删除后，该规则将不再生效。', onOk: () => { dispatch({ type: 'agent.config', id: agent.id, config: updateGuards(agent.draft, agent.draft.guards.filter((guard) => guard.id !== item.id)) }); toast.success('防护措施已删除'); } })}>删除防护措施</Menu.Item></Menu>;
  return <div className="detail-resource-page"><div className="detail-toolbar"><h1 className="resource-page-title">防护措施</h1><Button type="primary" icon={<IconPlus />} onClick={() => openEdit()}>新建防护措施</Button></div><Table rowKey="id" dataSource={agent.draft.guards} pagination={false} columns={[{ title: '名称', dataIndex: 'name' }, { title: '启用状态', dataIndex: 'enabled', render: (value: boolean, item: Guard) => <Switch checked={value} onChange={(checked) => toggleEnabled(item, checked)} aria-label={`${item.name} 启用状态`} /> }, { title: '最近更新', dataIndex: 'updatedAt', render: formatDate }, { title: '操作', width: 72, render: (_: unknown, item: Guard) => <Dropdown droplist={more(item)} trigger="click"><Button type="text" className="table-more-button" icon={<IconMore />} aria-label={`${item.name} 更多操作`} /></Dropdown> }]} /><Modal open={open} title={editing ? '编辑防护措施' : '新建防护措施'} onCancel={() => setOpen(false)} onOk={save} okText="保存"><Form form={form} layout="vertical"><Form.Item name="name" label="防护措施名称" rules={[{ required: true, message: '请输入名称' }]}><Input /></Form.Item><Form.Item name="prompt" label="提示词" rules={[{ required: true, message: '请输入提示词' }]}><Input.TextArea rows={4} /></Form.Item><Form.Item name="action" label="违规时操作" rules={[{ required: true }]}><Select onChange={(value: Guard['action']) => { setAction(value); if (value === 'end') form.setFieldValue('fixedReply', ''); }} options={[{ label: '结束会话', value: 'end' }, { label: '回复固定话术', value: 'fixed' }]} /></Form.Item>{action === 'fixed' && <Form.Item name="fixedReply" label="回复话术"><Input.TextArea rows={3} /></Form.Item>}<Form.Item name="enabled" label="启用状态" valuePropName="checked"><Switch /></Form.Item></Form></Modal></div>;
}

export function VariablesSectionV2({ agent }: { agent: Agent }) {
  const { dispatch } = useAppStore(); const toast = Message; const [open, setOpen] = useState(false); const [editing, setEditing] = useState<EnvironmentVariable>(); const [form] = Form.useForm();
  const save = async () => { const values = await form.validateFields(); if (agent.draft.variables.some((item) => item.name === values.name && item.id !== editing?.id)) { toast.error('同一智能体下变量不可重复'); return; } const item: EnvironmentVariable = { id: editing?.id || makeId('var'), name: values.name, value: values.value, description: values.description || '', updatedAt: now() }; const variables = editing ? agent.draft.variables.map((variable) => variable.id === editing.id ? item : variable) : [...agent.draft.variables, item]; dispatch({ type: 'agent.config', id: agent.id, config: { ...agent.draft, variables } }); setOpen(false); toast.success('环境变量已保存'); };
  const openEdit = (item?: EnvironmentVariable) => { setEditing(item); form.resetFields(); if (item) form.setFieldsValue(item); setOpen(true); };
  const more = (item: EnvironmentVariable) => <Menu><Menu.Item key="edit" onClick={() => openEdit(item)}>编辑</Menu.Item><Menu.Item key="delete" className="danger-menu-item" onClick={() => Modal.confirm({ title: '删除环境变量？', content: '删除后，引用该变量的配置可能无法正常工作。', onOk: () => { dispatch({ type: 'agent.config', id: agent.id, config: { ...agent.draft, variables: agent.draft.variables.filter((variable) => variable.id !== item.id) } }); toast.success('环境变量已删除'); } })}>删除环境变量</Menu.Item></Menu>;
  return <div className="detail-resource-page"><div className="detail-toolbar"><h1 className="resource-page-title">环境变量</h1><Button type="primary" icon={<IconPlus />} onClick={() => openEdit()}>新建变量</Button></div><Table rowKey="id" dataSource={agent.draft.variables} pagination={false} columns={[{ title: '变量', dataIndex: 'name', render: (value: string) => <span className="mono">{`{{${value}}}`}</span> }, { title: '值', dataIndex: 'value', render: (value: string) => <span className="mono">{value}</span> }, { title: '描述', dataIndex: 'description' }, { title: '最近更新', dataIndex: 'updatedAt', render: formatDate }, { title: '操作', width: 72, render: (_: unknown, item: EnvironmentVariable) => <Dropdown droplist={more(item)} trigger="click"><Button type="text" className="table-more-button" icon={<IconMore />} aria-label={`${item.name} 更多操作`} /></Dropdown> }]} /><Modal open={open} title={editing ? '编辑环境变量' : '新建环境变量'} onCancel={() => setOpen(false)} onOk={save} okText="保存"><Form form={form} layout="vertical"><Form.Item name="name" label="变量" rules={[{ required: true, message: '请输入变量名称' }, { pattern: /^[A-Z_][A-Z0-9_]*$/, message: '仅支持英文大写字母、数字和下划线，且不能以数字开头' }]}><Input placeholder="API_KEY" /></Form.Item><Form.Item name="value" label="值" rules={[{ required: true, message: '请输入变量值' }]}><Input.Password /></Form.Item><Form.Item name="description" label="描述"><Input /></Form.Item></Form></Modal></div>;
}

function MetricCards({ sessions }: { sessions: Session[] }) { const metrics = [{ label: '会话数', value: sessions.length }, { label: '消息数', value: sessions.reduce((sum, item) => sum + item.messageCount, 0) }, { label: '转人工数', value: sessions.filter((item) => item.status === 'human').length }, { label: '异常数', value: sessions.filter((item) => item.status === 'error').length }, { label: '平均响应时长', value: '1.8s' }]; return <div className="metric-grid">{metrics.map((metric) => <div className="metric-card" key={metric.label}><div className="metric-label">{metric.label}</div><div className="metric-value">{metric.value}</div></div>)}</div>; }

export function MonitorSectionV2({ agent, mode }: { agent: Agent; mode: 'overview' | 'sessions' }) {
  const { state } = useAppStore(); const [channel, setChannel] = useState('全部渠道'); const [status, setStatus] = useState('全部状态'); const [hit, setHit] = useState('全部命中'); const [selected, setSelected] = useState<Session>(); const channels = state.channels.filter((item) => item.agentId === agent.id); const sessions = state.sessions.filter((item) => item.agentId === agent.id && (channel === '全部渠道' || item.channel === channel) && (status === '全部状态' || item.status === status) && (hit === '全部命中' || item.hits.some((value) => value.includes(hit))));
  const channelOptions = [{ value: '全部渠道', label: '全部渠道' }, ...channels.map((item) => ({ value: item.name, label: item.name }))];
  const filter = <div className="detail-monitor-filters"><Select value={channel} onChange={setChannel} options={channelOptions} style={{ width: 160 }} /><Select value={status} onChange={setStatus} options={[['全部状态', '全部状态'], ['active', '进行中'], ['ended', '已结束'], ['human', '已转人工'], ['error', '异常']].map(([value, label]) => ({ value, label }))} style={{ width: 130 }} /><Select value={hit} onChange={setHit} options={['全部命中', '流程', '知识', '技能', '防护措施', '转人工', '模型异常'].map((value) => ({ value, label: value }))} style={{ width: 130 }} /><DatePicker.RangePicker /></div>;
  if (mode === 'sessions') return <div className="detail-monitor-page">{filter}<Table rowKey="id" dataSource={sessions} pagination={false} columns={[{ title: '用户 / 会话标题', dataIndex: 'title' }, { title: '渠道', dataIndex: 'channel' }, { title: '开始时间', dataIndex: 'startedAt' }, { title: '消息数', dataIndex: 'messageCount' }, { title: '会话状态', dataIndex: 'status', render: (value: Session['status']) => <Tag color={value === 'error' ? 'red' : value === 'human' ? 'orange' : value === 'ended' ? 'green' : 'arcoblue'}>{value === 'active' ? '进行中' : value === 'ended' ? '已结束' : value === 'human' ? '已转人工' : '异常'}</Tag> }, { title: '操作', width: 72, render: (_: unknown, item: Session) => <Dropdown droplist={<Menu><Menu.Item key="view" onClick={() => setSelected(item)}>查看详情</Menu.Item></Menu>} trigger="click"><Button type="text" className="table-more-button" icon={<IconMore />} aria-label={`${item.title} 更多操作`} /></Dropdown> }]} /><SessionDrawer session={selected} agent={agent} onClose={() => setSelected(undefined)} /></div>;
  const list = (items: string[]) => <div className="monitor-list">{items.map((name) => <div className="monitor-list-item" key={name}><span>{name}</span><span className="mono">{sessions.filter((session) => session.hits.some((hitValue) => hitValue.includes(name))).length} 次</span></div>)}</div>;
  return <div className="detail-monitor-page">{filter}<MetricCards sessions={sessions} /><div className="monitor-panels"><Card className="section-card" title="流程触发 Top">{list(agent.draft.flows.map((flow) => flow.name))}</Card><Card className="section-card" title="技能触发 Top">{list(state.skills.filter((skill) => agent.draft.skillIds.includes(skill.id)).map((skill) => skill.name))}</Card><Card className="section-card" title="防护措施触发 Top">{list(agent.draft.guards.map((guard) => guard.name))}</Card><Card className="section-card" title="异常类型分布">{list(['模型异常', '技能调用异常', '渠道发送异常', '知识检索异常'])}</Card></div></div>;
}

function SessionDrawer({ session, agent, onClose }: { session?: Session; agent: Agent; onClose: () => void }) { return <Drawer open={Boolean(session)} onCancel={onClose} title="会话详情" width={560} footer={null} maskClosable escToExit>{session && <><Descriptions column={1} items={[{ key: 'title', label: '会话标题', children: session.title }, { key: 'channel', label: '渠道', children: session.channel }, { key: 'agent', label: '接待智能体', children: agent.name }, { key: 'started', label: '开始时间', children: session.startedAt }, { key: 'status', label: '会话状态', children: session.status }]} /><Divider /><h3>对话内容</h3><div className="session-messages">{session.messages.map((item, index) => <div className="session-message" key={index}><Tag>{item.role === 'user' ? '用户' : item.role === 'agent' ? '智能体' : '系统事件'}</Tag><span>{item.content}</span></div>)}</div><Divider /><h3>命中详情</h3><div className="hit-list">{session.hits.map((hit) => <div className="hit-item" key={hit}>{hit}</div>)}</div></>}</Drawer>; }
